### ISSUE TITLE
[BUG] Awful Snap Bug Title Here

### ISSUE THREAD

**Issue by wireinet** [snapcrafters/alacritty#22]
**Describe the bug**

If i install alacritty by snap, i have problems with pemissions

**To Reproduce**
sudo snap install alacritty --classic
Create config by path ~/.config/alacritty/alacritty.toml
try to install themes

add same config is ok, but if i want to use themes:
instal curv:
1 sudo snap install curl,
install themes
2 curl -LO --output-dir ~/.config/alacritty https://github.com/catppuccin/alacritty/raw/main/catppuccin-latte.toml
have error:
/home/myname/.config/alacritty/catppuccin-latte.toml: Permission 
Warning: denied

**Expected behavior**

want to get no permission errors

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04.3 LTS]
 - Alacritty Version: 
 - Graphics Cards: 

**Additional context**

Shell output:

```
$ alacritty -vvv
...
```

LIBGL_DEBUG output (only if you have graphics related issue):

```
$ LIBGL_DEBUG=verbose alacritty
...
```

**Comment by popey** [comment]
This is because you used a confined version of curl, not a bug in alacritty. 

Use some other method of installing curl, not the snap. Because the confined curl binary will not have access to hidden folders in your home directory.
