### ISSUE TITLE
[BUG] Awful Snap Bug Title Here

### ISSUE THREAD

**Issue by Abdiraxiimabdixakiim** [snapcrafters/alacritty#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04.3 LTS]
 - Alacritty Version: 
 - Graphics Cards: 

**Additional context**

Shell output:

```
$ alacritty -vvv
...
```

LIBGL_DEBUG output (only if you have graphics related issue):

```
$ LIBGL_DEBUG=verbose alacritty
...
```

**Comment by jnsgruk** [comment]
Hi, this bug doesn't seem to have any information in it about the actual bug - could you please elaborate?

**Comment by soumyaDghosh** [comment]
May be this is a joke?
