### ISSUE TITLE
[BUG] 'Update' GitHub Actions workflow is not being executed anymore

### ISSUE THREAD

**Issue by Programie** [snapcrafters/alacritty#31]
**Describe the bug**

The [Update](https://github.com/snapcrafters/alacritty/actions/workflows/sync-upstream.yml) GitHub Actions workflow is not being executed anymore. Therefore, the recently released version [0.14.0](https://github.com/alacritty/alacritty/releases/tag/v0.14.0) is not pulled from the Alacritty repository.

**To Reproduce**

1. Go to the [Actions > Update](https://github.com/snapcrafters/alacritty/actions/workflows/sync-upstream.yml) of this repository
2. There is a notice showing `This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.`

**Expected behavior**

The latest release of Alacritty should be pulled and suggested as a new release for this Snap.

**Screenshots**

![image](https://github.com/user-attachments/assets/0dff4ca4-843f-448e-9ebe-1fd045797179)

**Comment by jnsgruk** [comment]
Fixed, thank you for reporting this! 🙂
